export const CHANGE_PANE = "CHANGE_PANE"

export const FETCH_ADDRESS_SUCCESS = "FETCH_ADDRESS_SUCCESS"
export const DA_OPEN_NEW_ADDRESS_FORM = "DA_OPEN_NEW_ADDRESS_FORM"
export const DA_SAVE_EDIT_ADDRESS = "DA_SAVE_EDIT_ADDRESS";
export const DA_SAVE_NEW_ADDRESS = "DA_SAVE_NEW_ADDRESS";
export const DA_CANCEL_ADD_NEW = "DA_CANCEL_ADD_NEW"
export const DA_DELETE_ADDRESS = "DA_DELETE_ADDRESS";
export const DA_TOGGLE_LOADING = "DA_TOGGLE_LOADING"

export const O_FETCH_ORDERS_SUCCESS = "O_FETCH_ORDERS_SUCCESS"
export const O_TOGGLE_LOADING = "O_TOGGLE_LOADING" 

// export const P_FETCH_PAYMENTS_SUCCESS = "P_FETCH_PAYMENTS_SUCCESS"

// export const R_FETCH_REFUNDS_SUCCESS = "R_FETCH_REFUNDS_SUCCESS"