export const CHANGE_PANE = "CHANGE_PANE"

export const FETCH_ADDRESS_SUCCESS = "FETCH_ADDRESS_SUCCESS"
export const DA_OPEN_NEW_ADDRESS_FORM = "DA_OPEN_NEW_ADDRESS_FORM"
export const DA_SAVE_EDIT_ADDRESS = "DA_SAVE_EDIT_ADDRESS";
export const DA_SAVE_NEW_ADDRESS = "DA_SAVE_NEW_ADDRESS";
export const DA_CANCEL_ADD_NEW = "DA_CANCEL_ADD_NEW"
export const DA_DELETE_ADDRESS = "DA_DELETE_ADDRESS";