export const FETCH_WISHLIST_SUCCESS = "FETCH_WISHLIST_SUCCESS"
export const ADD_CART_DELETE_WISHLIST_SUCCESS = "ADD_CART_DELETE_WISHLIST_SUCCESS"
export const DELETE_WISHLIST_SUCCESS = "DELETE_WISHLIST_SUCCESS"
export const TOGGLE_WISHLIST_LOADING = "TOGGLE_WISHLIST_LOADING"