export const FETCH_COLLECTION = "FETCH_COLLECTION"
export const FETCH_COLLECTION_SUCCESS = "FETCH_COLLECTION_SUCCESS"
export const FETCH_COLLECTION_FAIL = "FETCH_COLLECTION_FAIL"
export const TOGGLE_COLLECTION_LOADING = "TOGGLE_COLLECTION_LOADING" 