export const FETCH_NEW_PRODUCTS = "FETCH_NEW_PRODUCTS"
export const FETCH_NEW_PRODUCTS_SUCCESS = "FETCH_NEW_PRODUCTS_SUCCESS"
export const FETCH_NEW_PRODUCTS_FAIL = "FETCH_NEW_PRODUCTS_FAIL"
export const TOGGLE_NEW_PRODUCTS_LOADING = "TOGGLE_NEW_PRODUCTS_LOADING"