export const LOGOUT = "LOGOUT";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ATTEMPT = "LOGIN_ATTEMPT";
export const OPEN_LOGIN_MODAL = "OPEN_LOGIN_MODAL";
export const CLOSE_LOGIN_MODAL = "CLOSE_LOGIN_MODAL";
export const OPEN_SIGNUP_MODAL = "OPEN_SIGNUP_MODAL";
export const CLOSE_SIGNUP_MODAL = "CLOSE_SIGNUP_MODAL";

export const SIGNUP_INVALID_EMAIL = "SIGNUP_INVALID_EMAIL";
export const SIGNUP_INVALID_PHONE = "SIGNUP_INVALID_PHONE";
export const SIGNUP_INVALID_PW = "SIGNUP_INVALID_PW";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";
export const CLEAR_SIGNUP = "CLEAR_SIGNUP";
export const RESET_SIGNUP_TEXT = "RESET_SIGNUP_TEXT"

export const SET_DETAILS = "SET_DETAILS"
