export const DOMAIN = "http://localhost:8000"
export const STRIPE_PK = "pk_test_51HoSBoEH2zpc9mRP6H0kPlnLL5V82dZSMYqvnl3L9JwnDDo4Rfgr6UNwu9HaMXtI7LwKJaSODX4QZkZYx3596pZz00opn1fib2"
export const YT_VIDEO_CODE = "z9aAjtmrz90"
export const home_quotes = ['quote 1', 'quote 2']
export const home_img1_quote = 'img1 _ quote something random'
export const home_img2_quote = 'img2 _ random something quote'
export const home_img1_btn_redirect = '/something';
export const home_img2_btn_redirect = '/something-else';
export const home_img1_url = "https://www.itl.cat/pngfile/big/210-2102958_dark-desk-laptop-macbook-room-table-technology-desk.jpg";
export const home_img2_url = "https://www.itl.cat/pngfile/big/210-2102958_dark-desk-laptop-macbook-room-table-technology-desk.jpg"
export const email_address = "somerandomemail@gmail.com"
export const instagram_username = "@username"
export const helpline_number = "9876543210"
export const instagram_link = "https://www.instagram.com/"
export const contact_img_url = "https://www.itl.cat/pngfile/big/210-2102958_dark-desk-laptop-macbook-room-table-technology-desk.jpg"