export const DOMAIN = "http://localhost:8000"
export const YT_VIDEO_CODE = "D0UnqGm_miA"
export const home_quotes = ['Lorem ipsum dolor sit amet - This is a quote']
export const home_img1_quote = 'Check out our new collection!'
export const home_img2_quote = 'Our trending items may interest you - Buy Now!'
export const home_img1_btn_redirect = '/collection';
export const home_img2_btn_redirect = '/trending';
export const home_img1_url = "https://www.pixelstalk.net/wp-content/uploads/2016/07/Wallpapers-HD-1080P-3D-Download.jpg";
export const home_img2_url = "https://www.itl.cat/pngfile/big/210-2102958_dark-desk-laptop-macbook-room-table-technology-desk.jpg"
export const email_address = "dummyemail@gmail.com"
export const instagram_username = "@instagram_username"
export const helpline_number = "9876543210"
export const instagram_link = "https://www.instagram.com/"
export const contact_img_url = "https://www.itl.cat/pngfile/big/210-2102958_dark-desk-laptop-macbook-room-table-technology-desk.jpg"
export const RAZORPAY_PK = "rzp_test_gKZGVUDmysPjSX"
export const razorpay_name = "Webshop"
export const razorpay_desc = "Get quality products here"